.TH "pipebench" "1" "18th Apr, 2003" "pipebench" "" 
.PP 
.SH "NAME" 
pipebench \- Shows speed of stdin/stdout communication
.PP 
.SH "SYNOPSIS" 
\fBpipebench\fP [ -ehqQor ] [ -s \fIfile\fP | -S \fIfile\fP ] [ -b \fIbufsize\fP ]
.PP 
.SH "DESCRIPTION" 
Measures the speed of stdin/stdout communication\&.
.PP 
.SH "OPTIONS" 
.PP 
.IP 
.IP "-h" 
Displays a help message and exits\&.
.IP "-e" 
If an error occurs, exit (breaking the pipe between stdin and
stdout\&. By default an error message is printed to stderr and the
program continues\&.
.IP "-q" 
Only show summary stats\&.
.IP "-Q" 
Don\&'t show running speed or summary stats\&. Same as -q -o\&. Can be
used to play with buffer size\&.
.IP "-o" 
Don\&'t show summary\&.
.IP "-b \fIbufsize\fP" 
Use this buffer size, in bytes\&.
.IP "-r" 
Just show raw speed, no fancy stuff\&. And no summary\&.
.IP "-s \fIfile\fP" 
Write status to \fIfile\fP instead of stderr\&.
.IP "-S \fIfile\fP" 
Write status to \fIfile\fP instead of stderr\&.
.IP "-I" 
Use 1kB = 1000B, instead of the default 1024B\&.
.IP 
.SH "EXAMPLES" 
\fBBenchmark and show progress of backup\fP 
.br 
# (cd /home/; tar cf - \&.) | pipebench | (cd /mnt/backup/; tar xf -) 
.br 
.IP 
.SH "" 
\fBA number to brag to your friends about\fP 
.br 
$ dd if=/dev/zero bs=80k count=60k 2> /dev/null | \&./pipebench -q > /dev/null
.IP 
.SH "BUGS" 
No known bugs\&.\&.\&. yet\&.
.IP 
.SH "SEE ALSO" 
\fBdd(1)\fP, \fBcat(1)\fP
.IP 
.SH "AUTHOR" 
Pipebench was written by Thomas Habets <thomas@habets\&.pp\&.se>
